--- #YAML:1.0
name:                PerlSpec
version:             0.1.0
abstract:            ~
license:             ~
author:              
    - Matthew Boston <matthew.boston@gmail.com>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    version:                       0.77
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
